login:
    path: /login
    controller: App\Controller\AuthorizationController::login

registration:
  path: /registration
  controller: App\Controller\RegistrationController::index

user:
  path: /user
  controller: App\Controller\UserController::index